
# @name login
POST {{$dotenv avictl}}/login HTTP/1.1
Accept: application/json,text/plain,*/*
Host: {{$dotenv hostname}}
Referer: {{$dotenv avictl}}
X-Avi-Version: {{$dotenv apiversion}}
Content-Type: application/json;charset=utf-8
Cookie: avi-sessionid=

{
    "username": "{{$dotenv user}}",
    "password": "{{$dotenv awstoken}}"
}

###
@csrf = 4YgzN21UABfWzi47YMCtHb6UspvB2NpS
#<-- Have to copy/paste this from the Set-Cookie in the login response
# @name pool
POST {{$dotenv avictl}}/api/pool HTTP/1.1
Accept: application/json,text/plain,*/*
X-Avi-Version: {{$dotenv apiversion}}
X-CSRFToken: {{csrf}}
Content-Type: application/json;charset=utf-8
Referer: https://{{$dotenv avictl}}/

{
      "name": "{{$dotenv poolname}}",
      "cloud_ref": "https://{{$dotenv avictl}}/api/cloud/?name={{$dotenv cloud_aws}}",
      "tenant_ref": "admin",
      "enable_http2": false,
      "servers": [
        {
            "ip": {
                "type": "V4",
                "addr": "{{$dotenv server1}}"
            },
            "enabled": true,
            "port": 81
        },
        {
            "ip": {
                "type": "V4",
                "addr": "{{$dotenv server2}}"
            },
            "enabled": true,
            "port": 80
        }
    ]
}
