# @name login
POST {{$dotenv avictl}}/login HTTP/1.1
Accept: application/json,text/plain,*/*
Host: {{$dotenv hostname}}
Referer: {{$dotenv avictl}}
X-Avi-Version: {{$dotenv apiversion}}
Content-Type: application/json;charset=utf-8
Cookie: avi-sessionid=

{
    "username": "{{$dotenv user}}",
    "password": "{{$dotenv awstoken}}"
}

###
@csrf = iV9LyBUFJ3QxDdAZijg0qYn9AcUHhqe1
#<-- Have to copy/paste this from the Set-Cookie in the login response

# @name vsvip
POST {{$dotenv avictl}}/api/vsvip HTTP/1.1
Accept: application/json,text/plain,*/*
X-Avi-Version: {{$dotenv apiversion}}
X-CSRFToken: {{csrf}}
Content-Type: application/json;charset=utf-8
Referer: https://{{$dotenv avictl}}/

{
    "name": "test2",
    "cloud_ref": "/api/cloud?name={{$dotenv cloud_aws}}",
    "vip": [
        {
            "auto_allocate_floating_ip": true,
            "enabled": true,
            "vip_id": "1",
            "ip_address": {
                "type": "V4",
                "addr": "10.0.1.145"
            }
        }
    ]
}



